# Generated by Django 4.1.7 on 2023-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fechaHora',
            field=models.DateTimeField(null=True),
        ),
    ]
